name: nextjs build
on:
  push:
    branches: [main]
jobs:
  caches_and_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6-beta
      - name: nodejs setup
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.x
          cache: 'npm'
      - name: install deps
        run: npm install --legacy-peer-deps
        
      - name: build setup
        run: npm run build
        
      - name: upload artifacts
        uses: actions/upload-artifact@v5.0.0
        with: 
          name: nxtb
          path: out/


          
          path : out/
          
       
       
