name: nextjs build
on:
  push:
    branches: [main]
jobs:
  caches_and_artifacts:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
      cancel-in-progress: true
    steps:
      - name: checkout action
        uses: actions/checkout@v6-beta
      - name: nodejs setup
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.x
          cache: 'npm'
      - name: install deps
        run: npm install 
        
      - name: build setup
        run: npm run build
        
      - name: upload artifacts
        uses: actions/upload-artifact@v5.0.0
        with: 
          name: nxtb
          path: out/ 
